# https://github.com/bahmutov/netlify-plugin-github-dispatch
[[plugins]]
  package = "netlify-plugin-github-dispatch"
  [plugins.inputs]
    owner = "jjhelguero" # use the target organization name
    repo = "app-netlify-cypress-tests" # use the target repo name
    workflow = ".github/workflows/e2e.yml" # use workflow relative path